###############################################################################
# Copyright (c) 2022 Mekdam Holding Group QPSC.                               #
# All rights reserved                                                         #
###############################################################################
server:
  port: 8043
  servlet:
    context-path: /test